name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test code
        runs-on: ubuntu-latest

        steps:
            - name: Check out the code
              uses: actions/checkout@v4

            - name: Set up NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm --prefix=api ci

            - name: Tests linting
              run: npm --prefix=api run eslint

            - name: Run tests
              run: npm --prefix=api run test
